export const products = [
    {
      id: 1,
      name: "Bunga",
      category: "Matahari",
      price: 30000,
      image: "/images/bunga1.jpg",
      isCart: false,
      description: "bunga merupakan bunga indah yang dapat menarik kumbang",
    },
    {
      id: 2,
      name: "Bunga",
      category: "Mawar",
      price: 40000,
      image: "/images/bunga2.jpg",
      isCart: false,
      description: "bunga memiliki bau yang harum",
    },
    {
      id: 3,
      name: "Dinosaurus",
      category: "Gantungan Kunci",
      price: 5000,
      image: "/images/dino.jpg",
      isCart: false,
      description: "Gantungan Kunci Dinosaurus dengan berbagai warna yang lucu",
    },
    {
      id: 4,
      name: "Koala",
      category: "Gantungan Kunci",
      price: 7600,
      image: "/images/koala.jpg",
      isCart: false,
      description: "Gantungan Kunci Koala dengan berbagai warna yang lucu",
    },
    {
      id: 5,
      name: "Pot",
      category: "Pot Cantik",
      price: 550000,
      image: "/images/potcantik.jpg",
      isCart: false,
      description: "Pot bunga untuk hiasan luar ruangan",
    },
    {
      id: 6,
      name: "Alat Siram",
      category: "Alat Siram Unik",
      price: 60000,
      image: "/images/alatsiram.jpg",
      isCart: false,
      description: "Alat siram yang unik agar semakin semangat menyiram tanaman",
    },
    {
      id: 7,
      name: "Rak Bunga",
      category: "Rak Bunga",
      price: 75000,
      image: "/images/rakbunga.jpg",
      isCart: false,
      description: "Rak bunga untuk menambah kerapian letak pot",
    },
];  