export const products = [
    {
      id: 1,
      name: "Bunga",
      category: "Matahari",
      price: 30000,
      image: "/images/bunga1.jpg",
      isCart: false,
      description: "bunga merupakan bunga indah yang dapat menarik kumbang",
    },
    {
      id: 2,
      name: "Bunga",
      category: "Mawar",
      price: 40000,
      image: "/images/bunga2.jpg",
      isCart: false,
      description: "bunga memiliki bau yang harum",
    },
    {
      id: 3,
      name: "Bunga",
      category: "Putih",
      price: 50000,
      image: "/images/bunga3.jpg",
      isCart: false,
      description: "Mawar putih adalah mawar berwarna putih nan harum",
    },
    {
      id: 4,
      name: "Guci Bunga",
      category: "Wadah Bunga",
      price: 760000,
      image: "/images/guci biru.jpg",
      isCart: false,
      description: "Guci bunga sebagai wadah bunga yang akan menambah nilai kecantikan bunga tersebut",
    },
    {
      id: 5,
      name: "Pot",
      category: "Pot Cantik",
      price: 550000,
      image: "/images/potcantik.jpg",
      isCart: false,
      description: "Pot bunga untuk hiasan luar ruangan",
    },
    {
      id: 6,
      name: "Alat Siram",
      category: "Alat Siram Unik",
      price: 60000,
      image: "/images/alatsiram.jpg",
      isCart: false,
      description: "Alat siram yang unik agar semakin semangat menyiram tanaman",
    },
    {
      id: 7,
      name: "Rak Bunga",
      category: "Rak Bunga",
      price: 75000,
      image: "/images/rakbunga.jpg",
      isCart: false,
      description: "Rak bunga untuk menambah kerapian letak pot",
    },
];  